//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillCancelSummary
    {
        public int BillCancelSummaryId { get; set; }
        public int BillNumber { get; set; }
        public System.DateTime CancelDate { get; set; }
        public int CancelBy { get; set; }
        public System.DateTime CancelByDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public Nullable<int> Branch { get; set; }
        public Nullable<int> FiscalYearId { get; set; }
        public Nullable<decimal> BillTotalAmount { get; set; }
        public string Remarks { get; set; }
        public string Narration { get; set; }
        public string Narration2 { get; set; }
        public Nullable<int> ApprovedStatus { get; set; }
    }
}
