//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodTransectionDetail
    {
        public int BloodTransectionDetailId { get; set; }
        public Nullable<int> BloodTransectionMasterId { get; set; }
        public string PouchNumber { get; set; }
        public Nullable<decimal> QuantityML { get; set; }
        public Nullable<int> QuantityUnit { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual BloodTransectionMaster BloodTransectionMaster { get; set; }
    }
}
