//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodTransectionMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BloodTransectionMaster()
        {
            this.BloodTransectionDetails = new HashSet<BloodTransectionDetail>();
        }
    
        public int BloodTransectionMasterId { get; set; }
        public int DepartmentId { get; set; }
        public int PatientId { get; set; }
        public Nullable<int> BloodTypeId { get; set; }
        public string ReferBy { get; set; }
        public System.DateTime RequiredDate { get; set; }
        public string Purpose { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BloodTransectionDetail> BloodTransectionDetails { get; set; }
    }
}
