//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodStockManagement
    {
        public int BloodStockId { get; set; }
        public Nullable<int> BloodType { get; set; }
        public Nullable<int> QuantityUnit { get; set; }
        public Nullable<decimal> QuantityML { get; set; }
        public string PouchNumber { get; set; }
        public Nullable<System.DateTime> StockDate { get; set; }
        public Nullable<System.DateTime> ValidUpTo { get; set; }
        public Nullable<int> SourceFrom { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
