//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodDonate
    {
        public int BloodDonateId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public int Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> District { get; set; }
        public Nullable<int> Zone { get; set; }
        public string Vdc { get; set; }
        public string Country { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public int BloodGroup { get; set; }
        public int Quantity { get; set; }
        public System.DateTime DonateDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<decimal> QuantityML { get; set; }
        public string PouchNumber { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
