//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CbDeptRefTable
    {
        public int CentralizedBillingDeptId { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Type { get; set; }
        public string Remarks { get; set; }
    }
}
