//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentralizedBilling
    {
        public int CentralizedBillingId { get; set; }
        public int AccountHeadId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime AmountDate { get; set; }
        public string PaymentType { get; set; }
        public string Narration1 { get; set; }
        public string Narration2 { get; set; }
        public string DepartmentName { get; set; }
        public int SubDepartmentId { get; set; }
        public string BillNumber { get; set; }
        public int LedgerMasterId { get; set; }
        public int PatientLogId { get; set; }
        public int PatientId { get; set; }
        public string JVNumber { get; set; }
        public Nullable<bool> JVStatus { get; set; }
        public Nullable<int> CreatedDepartmentId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Remarks { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> PaidOnPaid { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<decimal> ItemDiscountPercentage { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
