//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentralizedBillingMaster
    {
        public int CentralizedBillingId { get; set; }
        public int BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public Nullable<decimal> TotalBillAmount { get; set; }
        public Nullable<int> TotalDiscountID { get; set; }
        public Nullable<decimal> TotalDiscountAmount { get; set; }
        public string Narration1 { get; set; }
        public string Narration2 { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> SubDepartmentId { get; set; }
        public int PatientLogId { get; set; }
        public int PatientId { get; set; }
        public string JVNumber { get; set; }
        public Nullable<bool> JVStatus { get; set; }
        public Nullable<int> CreatedDepartmentId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Remarks { get; set; }
        public bool Status { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> ReceiptId { get; set; }
        public Nullable<bool> IsHandover { get; set; }
        public Nullable<decimal> TenderAmount { get; set; }
        public Nullable<decimal> ReturnedAmount { get; set; }
        public Nullable<int> PayableType { get; set; }
    }
}
