//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionDetaislByType
    {
        public int commissionDetailByTypeID { get; set; }
        public Nullable<int> commissionDetailsId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<int> CommissionTypeId { get; set; }
        public string CommissionTypeName { get; set; }
        public Nullable<int> BillNo { get; set; }
        public System.DateTime CommissionDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> AccountHeadId { get; set; }
        public Nullable<int> Branch { get; set; }
        public Nullable<bool> JvStatus { get; set; }
    }
}
