//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulation
    {
        public int Id { get; set; }
        public Nullable<int> EmergencyMasterId { get; set; }
        public Nullable<int> ConsulationId { get; set; }
        public string ConsulationText { get; set; }
        public string ProgressNotes { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
