//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CytologyReport
    {
        public int CytologyId { get; set; }
        public string CytopathNo { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> RefDocId { get; set; }
        public Nullable<long> RegId { get; set; }
        public Nullable<System.DateTime> DateOfReceipt { get; set; }
        public Nullable<System.DateTime> DateOfDispatch { get; set; }
        public string WardOrOpd { get; set; }
        public string ClinicalFeatures { get; set; }
        public string Speciman { get; set; }
        public string Site { get; set; }
        public string ProcedureNote { get; set; }
        public string MiicroDescription { get; set; }
        public string Diagnosis { get; set; }
        public string Comments { get; set; }
        public string Pathologists { get; set; }
        public string Resident { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
