//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyJvDetail
    {
        public int DailyJvDetailID { get; set; }
        public string Narration { get; set; }
        public string JvNo { get; set; }
        public System.DateTime Date { get; set; }
        public string DrCr { get; set; }
        public string AccountHead { get; set; }
        public decimal DrAmount { get; set; }
        public decimal CrAmount { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
