//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesignationWiseSalarySetup
    {
        public int ID { get; set; }
        public int DesignationID { get; set; }
        public decimal BasicSalary { get; set; }
        public decimal Grade { get; set; }
        public decimal LaganiKoshPercent { get; set; }
        public decimal LaganiKoshAmount { get; set; }
        public string Remarks { get; set; }
        public bool Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
