//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmergencyTreatmentAllergy
    {
        public int TreatmentAllergiesId { get; set; }
        public int EmergencyMasterId { get; set; }
        public string TreatmentText { get; set; }
        public string AllergiesText { get; set; }
        public string ProcedureText { get; set; }
        public Nullable<System.TimeSpan> TreatmentTime { get; set; }
        public string DrugsName { get; set; }
        public string DoseAndRoute { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public string Staff { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
