//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmergencyFeeDetail
    {
        public int EmergencyFeeDetailsId { get; set; }
        public Nullable<int> EmergencyMasterId { get; set; }
        public Nullable<decimal> RegistrationFee { get; set; }
        public Nullable<System.DateTime> FeeDate { get; set; }
        public Nullable<decimal> DoctorFee { get; set; }
        public Nullable<decimal> MemberDiscountAmount { get; set; }
        public Nullable<decimal> OtherDiscountPercentage { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> AccountHeadId { get; set; }
    
        public virtual EmergencyMaster EmergencyMaster { get; set; }
    }
}
