//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmergencyTriage
    {
        public int EmergencyTriageId { get; set; }
        public Nullable<int> EmergencyMasterId { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> MediumId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<int> sourceTypeId { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> TriageLevel { get; set; }
        public Nullable<int> MedicalOfficer { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual EmergencyMaster EmergencyMaster { get; set; }
    }
}
