//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmergencyMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmergencyMaster()
        {
            this.EmergencyFeeDetails = new HashSet<EmergencyFeeDetail>();
            this.EmergencyTriages = new HashSet<EmergencyTriage>();
            this.EmergencyTstCarids = new HashSet<EmergencyTstCarid>();
        }
    
        public int EmergencyMasterId { get; set; }
        public Nullable<int> EmergencyNumber { get; set; }
        public Nullable<int> OpdMasterId { get; set; }
        public Nullable<int> SerialNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> TimeIn { get; set; }
        public Nullable<System.TimeSpan> TimeOut { get; set; }
        public string ContactNumber { get; set; }
        public string BroughtBy { get; set; }
        public Nullable<int> RelationShip { get; set; }
        public string CheifComplainAndHistory { get; set; }
        public string ClinicalExamination { get; set; }
        public string FinalDiagnosis { get; set; }
        public Nullable<int> OutcomeTypeId { get; set; }
        public string OutcomeText { get; set; }
        public string DischargeConditionAndInst { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> Status { get; set; }
        public string Case { get; set; }
        public Nullable<System.DateTime> DischargeDate { get; set; }
        public Nullable<int> IcdCodeNumber { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmergencyFeeDetail> EmergencyFeeDetails { get; set; }
        public virtual EmergencyMaster EmergencyMaster1 { get; set; }
        public virtual EmergencyMaster EmergencyMaster2 { get; set; }
        public virtual EmergencyMaster EmergencyMaster11 { get; set; }
        public virtual EmergencyMaster EmergencyMaster3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmergencyTriage> EmergencyTriages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmergencyTstCarid> EmergencyTstCarids { get; set; }
    }
}
