//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        public int ID { get; set; }
        public int EmployeeMasterId { get; set; }
        public string CitizenshipNo { get; set; }
        public string MaritialStatus { get; set; }
        public int ReleaseDistrict { get; set; }
        public string PanNo { get; set; }
        public string InsuranceNo { get; set; }
        public string BloodGroup { get; set; }
        public string GrandFatherName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string WifeHusbandName { get; set; }
        public string NomineeName { get; set; }
        public string NomineeAddress { get; set; }
        public string NomineeRelation { get; set; }
        public string NomineePhoneNo { get; set; }
        public bool Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
