//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_AccSubGroups
    {
        public int AccSubGruupID { get; set; }
        public int AccGroupID { get; set; }
        public string AccSubGroupName { get; set; }
        public int ParentID { get; set; }
        public string HierarchyCode { get; set; }
        public int HeadLevel { get; set; }
        public string AccountCode { get; set; }
        public bool IsLeafLevel { get; set; }
        public bool Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
