//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_LedgerMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GL_LedgerMaster()
        {
            this.GL_Transaction = new HashSet<GL_Transaction>();
        }
    
        public int LedgerMasterID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string LedgerSourceType { get; set; }
        public Nullable<int> AccountGroupID { get; set; }
        public Nullable<int> AccountSubGroupID { get; set; }
        public Nullable<int> AccountTypeID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public string LedgerName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_Transaction> GL_Transaction { get; set; }
    }
}
