//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_Transaction
    {
        public int TransactionID { get; set; }
        public int DepartmentID { get; set; }
        public int VoucherNo { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int LedgerMasterID { get; set; }
        public string Narration1 { get; set; }
        public string Narration2 { get; set; }
        public decimal Amount { get; set; }
        public string Dr_Cr { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
        public Nullable<int> RefNo { get; set; }
        public int PatientLogId { get; set; }
        public Nullable<int> FeeTypeId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual GL_LedgerMaster GL_LedgerMaster { get; set; }
    }
}
