//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class IpdDischarge
    {
        public int IpdDischargeID { get; set; }
        public Nullable<int> ipdResistrationID { get; set; }
        public Nullable<int> DignosisID { get; set; }
        public string BriefHistory { get; set; }
        public string ClinicalFindings { get; set; }
        public string Investigation { get; set; }
        public string Medicinetreatment { get; set; }
        public string FurtherTreatment { get; set; }
        public string FoloowUp { get; set; }
        public Nullable<int> IpdPatientRoomDetailId { get; set; }
        public Nullable<int> IpdPatientBedDetailId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Dignosis { get; set; }
    }
}
