//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class IpdMrMedicineRecord
    {
        public int IpdMrMedicalRecordID { get; set; }
        public int IpdRegisterationID { get; set; }
        public int PatientID { get; set; }
        public string MedicineName { get; set; }
        public string Doses { get; set; }
        public string DosesTimes { get; set; }
        public string DosesTotalDays { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> Staff { get; set; }
        public string Shift { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
    }
}
