//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class IpdMRCommonTest
    {
        public int IpdMRCommonTestID { get; set; }
        public Nullable<int> IpdRegistrationID { get; set; }
        public Nullable<int> OpdID { get; set; }
        public string CommonTestName { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> IpdMRcCommonTesDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateByDate { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
