//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class IpdPatientBedDetail
    {
        public int IpdPatientBedDetailId { get; set; }
        public int IpdRegistrationId { get; set; }
        public int OpdEmergencyNumber { get; set; }
        public int BedNumber { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime AdmitedDate { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public bool Status { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsPaidBill { get; set; }
    
        public virtual IpdRegistrationMaster IpdRegistrationMaster { get; set; }
    }
}
