//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class IpdPatientDiagnosisDetail
    {
        public int IpdPatientDiagnosisDetailID { get; set; }
        public int IpdRegistrationID { get; set; }
        public int DiagnosisID { get; set; }
    }
}
