//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class IpdPatientroomDetail
    {
        public int IpdPatientRoomDetailId { get; set; }
        public int IpdRegistrationID { get; set; }
        public int OpdNoEmergencyNo { get; set; }
        public int WardNo { get; set; }
        public int RoomType { get; set; }
        public int RoomNo { get; set; }
        public int BedNo { get; set; }
        public bool Status { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual IpdRegistrationMaster IpdRegistrationMaster { get; set; }
    }
}
