//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class IpdRegistrationMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IpdRegistrationMaster()
        {
            this.IpdPatientBedDetails = new HashSet<IpdPatientBedDetail>();
            this.IpdPatientroomDetails = new HashSet<IpdPatientroomDetail>();
        }
    
        public int IpdRegistrationID { get; set; }
        public int OpdNoEmergencyNo { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedtBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> IcdCodeNumber { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> ReferDoctorId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IpdPatientBedDetail> IpdPatientBedDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IpdPatientroomDetail> IpdPatientroomDetails { get; set; }
    }
}
