//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class IpdRoomStatu
    {
        public int IPDRoomStatusId { get; set; }
        public int IPDRoomId { get; set; }
        public Nullable<int> RoomNumber { get; set; }
        public int BedNumber { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual SetUpIpdRoom SetUpIpdRoom { get; set; }
    }
}
