//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemBlockRecord
    {
        public int ItemBlcokRecID { get; set; }
        public int ItemBlockSetupID { get; set; }
        public string Particular { get; set; }
        public int SerialNo { get; set; }
        public string ItemName { get; set; }
        public int DepId { get; set; }
        public string Condition { get; set; }
        public string RoomNo { get; set; }
        public int SupplierId { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string Remarks { get; set; }
        public bool Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual ItemBlockSetup ItemBlockSetup { get; set; }
    }
}
