//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDemandDetail
    {
        public int ItemDemandDetailId { get; set; }
        public int ItemDemandID { get; set; }
        public int ItemID { get; set; }
        public decimal QuantityDemand { get; set; }
        public bool DispatchStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
