//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemAllotmentDetail
    {
        public int ItemAllotmentDetailID { get; set; }
        public int ItemAllotmentMasterID { get; set; }
        public int ItemID { get; set; }
        public decimal QuantityIssued { get; set; }
        public decimal QuantityRemained { get; set; }
        public int SourceFrom { get; set; }
        public bool CancellationStatus { get; set; }
        public string Remarks { get; set; }
        public bool Status { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
