//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemAllotmentMaster
    {
        public int ItemAllotmentMasterID { get; set; }
        public string ItemAllotmentNo { get; set; }
        public int ItemDemandID { get; set; }
        public System.DateTime AllotmentDate { get; set; }
        public string Orderer { get; set; }
        public string OrdererPost { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool Status { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
