//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class JornalVFormat
    {
        public int JVId { get; set; }
        public string Prefix { get; set; }
        public string FiscalYear { get; set; }
        public string Postfix { get; set; }
        public string JVFormat { get; set; }
        public string IsCurrent { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
