//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class JVDetail
    {
        public int JVDetailId { get; set; }
        public int JVMasterId { get; set; }
        public Nullable<int> FeeTypeId { get; set; }
        public Nullable<int> FeeTypeSubId { get; set; }
        public string FeeTypeName { get; set; }
        public Nullable<decimal> DrAmount { get; set; }
        public Nullable<decimal> CrAmount { get; set; }
        public string PaymentType { get; set; }
        public string BillNumber { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Narration { get; set; }
        public Nullable<int> LinkToDr { get; set; }
        public string DrOrCr { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual JVMaster JVMaster { get; set; }
    }
}
