//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class JVMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JVMaster()
        {
            this.JVDetails = new HashSet<JVDetail>();
        }
    
        public int JvMasterId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string JvNumber { get; set; }
        public string BillNumber { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> FiscalYearId { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public string Narration1 { get; set; }
        public string Narration2 { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string JvType { get; set; }
        public string FormName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JVDetail> JVDetails { get; set; }
    }
}
