//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalRecordDischarge
    {
        public int MedicalRecordId { get; set; }
        public int OpdId { get; set; }
        public int IPId { get; set; }
        public System.DateTime RegisteredDate { get; set; }
        public Nullable<System.DateTime> DischargeDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string ConditionAtDischarge { get; set; }
        public Nullable<int> ConditionAtDischargeId { get; set; }
        public Nullable<int> ICDCode { get; set; }
        public Nullable<int> DiagnosisCode { get; set; }
        public string Remarks { get; set; }
        public string Narration { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> DischargeDocId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
