//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpdFeeDetail
    {
        public int OpdFeeDetailsID { get; set; }
        public int OpdID { get; set; }
        public Nullable<decimal> RegistrationFee { get; set; }
        public Nullable<decimal> FeeTaxAmount { get; set; }
        public Nullable<System.DateTime> FeeDate { get; set; }
        public Nullable<decimal> DoctorFee { get; set; }
        public Nullable<decimal> DoctorFeeTax { get; set; }
        public Nullable<decimal> MemberDiscountAmount { get; set; }
        public Nullable<decimal> OtherDiscountPercentage { get; set; }
        public Nullable<decimal> OtherDiscountAmount { get; set; }
        public Nullable<decimal> Tender { get; set; }
        public Nullable<decimal> ReturnAmount { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<decimal> TotalAmountWithTax { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> BookFee { get; set; }
    
        public virtual OpdMaster OpdMaster { get; set; }
    }
}
