//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpdMedicalRecordMedicineRefer
    {
        public int OpdMRMedicineReferId { get; set; }
        public int OpdMedicalRecordMastetId { get; set; }
        public int PatientId { get; set; }
        public string MedicineName { get; set; }
        public string Doses { get; set; }
        public string DosesDay { get; set; }
        public string DosesTime { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool Status { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual OpdMedicalRecordMaster OpdMedicalRecordMaster { get; set; }
    }
}
