//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpdMedicalRecordMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OpdMedicalRecordMaster()
        {
            this.OpdMedicalRecordCommonTests = new HashSet<OpdMedicalRecordCommonTest>();
            this.OpdMedicalRecordFurtherTests = new HashSet<OpdMedicalRecordFurtherTest>();
            this.OpdMedicalRecordMedicineRefers = new HashSet<OpdMedicalRecordMedicineRefer>();
        }
    
        public int OpdMedicalRecordMastetId { get; set; }
        public int PatientId { get; set; }
        public int DepartmentId { get; set; }
        public int DoctorId { get; set; }
        public System.DateTime VisitedDate { get; set; }
        public string CurrentCase { get; set; }
        public string Remarks { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool Status { get; set; }
        public Nullable<int> PatientDoctorDetailID { get; set; }
        public string PreviousCase { get; set; }
        public string ProvisionalDiagnosis { get; set; }
        public Nullable<int> PatientLogId { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpdMedicalRecordCommonTest> OpdMedicalRecordCommonTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpdMedicalRecordFurtherTest> OpdMedicalRecordFurtherTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpdMedicalRecordMedicineRefer> OpdMedicalRecordMedicineRefers { get; set; }
    }
}
