//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpdMedicalRecordCommonTest
    {
        public int OpdMRCommonTestId { get; set; }
        public Nullable<int> OpdMedicalRecordMastetId { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string ShortDesc { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool Status { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual OpdMedicalRecordMaster OpdMedicalRecordMaster { get; set; }
    }
}
