//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpdPatientDoctorDetail
    {
        public int PatientDoctorDetailID { get; set; }
        public Nullable<int> OpdID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<System.TimeSpan> PreferTime { get; set; }
        public Nullable<System.DateTime> PreferDate { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual OpdMaster OpdMaster { get; set; }
    }
}
