//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpeningBalance
    {
        public int ID { get; set; }
        public int FiscalYear { get; set; }
        public int AccountHeadId { get; set; }
        public decimal DrAmount { get; set; }
        public decimal CrAmount { get; set; }
        public bool Status { get; set; }
    }
}
