//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationTheatreMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OperationTheatreMaster()
        {
            this.OperationRecords = new HashSet<OperationRecord>();
        }
    
        public int OperationTheatreMasterID { get; set; }
        public System.DateTime OperationDate { get; set; }
        public System.TimeSpan OperationStartTime { get; set; }
        public int OperationRoomID { get; set; }
        public System.TimeSpan OperationEndTime { get; set; }
        public Nullable<int> SourceID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool Status { get; set; }
        public Nullable<decimal> Charge { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalCharge { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string OperationType { get; set; }
        public string ChargeName { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationRecord> OperationRecords { get; set; }
    }
}
