//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationTheatreDetail
    {
        public int OperationTheatreDetailsID { get; set; }
        public int OperationTheatreMasterID { get; set; }
        public int PersonAllocatedID { get; set; }
        public int PersonAllocatedTypeID { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
