//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationRecord
    {
        public int OperationRecordId { get; set; }
        public string OpdId { get; set; }
        public string PreOperativeDiagnosis { get; set; }
        public string PostOperativeDiagnosis { get; set; }
        public string OperativeProcedure { get; set; }
        public string DescriptionOfOperation { get; set; }
        public string FindingProcedure { get; set; }
        public string Conditions { get; set; }
        public int OperationTheatreMasterId { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual OperationTheatreMaster OperationTheatreMaster { get; set; }
    }
}
