//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackagePatientAssignment
    {
        public int PackagePatientId { get; set; }
        public int PackageId { get; set; }
        public int OpdId { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool Status { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
