//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageDetail
    {
        public int PackageDetailId { get; set; }
        public int PackageId { get; set; }
        public int TestId { get; set; }
        public bool Status { get; set; }
        public int SectionId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> DeptId { get; set; }
    }
}
