//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientTestResult
    {
        public int PatientTestResultID { get; set; }
        public int PatientTestID { get; set; }
        public int PatientTestDetailID { get; set; }
        public int TestID { get; set; }
        public string Value1 { get; set; }
        public string Value2 { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
