//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientLogMaster
    {
        public int OpdMasterLogId { get; set; }
        public int PatientId { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public int DepartmentId { get; set; }
        public Nullable<int> OpdTypeID { get; set; }
        public bool Status { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
