//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDietDetail
    {
        public int PatientDietMasterId { get; set; }
        public int IPDRegistrationId { get; set; }
        public int OPDId { get; set; }
        public int DietTypeId { get; set; }
        public string Diet { get; set; }
        public System.DateTime DietDate { get; set; }
        public System.TimeSpan DietTime { get; set; }
        public int NurseInChargeId { get; set; }
        public string NurseName { get; set; }
        public int IsDietTaken { get; set; }
        public int Status { get; set; }
    }
}
