//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDepositMaster
    {
        public int PatientDepositMasterId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> PatientDepartmentId { get; set; }
        public string DepostedBy { get; set; }
        public Nullable<int> RelationId { get; set; }
        public decimal DepositedAmount { get; set; }
        public Nullable<System.DateTime> DepositedDate { get; set; }
        public string SwipeCardId { get; set; }
        public string SwipeCardDetail { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedDepartmentId { get; set; }
        public Nullable<int> DepositeType { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> ReceiptID { get; set; }
    }
}
