//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollMaster
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int MonthID { get; set; }
        public int YearID { get; set; }
        public decimal BasicSalary { get; set; }
        public Nullable<int> GradeNo { get; set; }
        public Nullable<decimal> GradeRate { get; set; }
        public Nullable<decimal> GradeAmount { get; set; }
        public Nullable<int> CITNo { get; set; }
        public Nullable<decimal> CITPercentage { get; set; }
        public Nullable<decimal> CITAmount { get; set; }
        public Nullable<int> PFNo { get; set; }
        public Nullable<decimal> PFAmount { get; set; }
        public Nullable<int> FundNo { get; set; }
        public Nullable<decimal> FundAmount { get; set; }
        public Nullable<int> BankID { get; set; }
        public string BankAccountNo { get; set; }
        public Nullable<decimal> LoanDeduction { get; set; }
        public Nullable<decimal> LoanInterest { get; set; }
        public Nullable<decimal> AdvanceDeduction { get; set; }
        public string InsuranceNo { get; set; }
        public Nullable<decimal> InsuranceAmount { get; set; }
        public Nullable<decimal> PFDeductAmount { get; set; }
        public Nullable<decimal> InsuranceDeductAmount { get; set; }
        public Nullable<decimal> SSTAmount { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> FestivalAmount { get; set; }
        public Nullable<int> BudgetID { get; set; }
        public Nullable<int> BudgetSubID { get; set; }
        public Nullable<int> FundID { get; set; }
        public Nullable<decimal> LeaveDeduction { get; set; }
        public Nullable<decimal> TotalAllowance { get; set; }
        public Nullable<decimal> TotalDeduction { get; set; }
        public string PresentDay { get; set; }
        public string OverTimeDuration { get; set; }
        public string OTHrDay { get; set; }
        public Nullable<decimal> OverTimeAmount { get; set; }
        public Nullable<decimal> EmpInsurancePaid { get; set; }
        public Nullable<decimal> RemoteAreaDeduction { get; set; }
        public Nullable<decimal> PhysicalDisability { get; set; }
        public Nullable<decimal> DressAllowance { get; set; }
        public Nullable<decimal> DearnessAllowance { get; set; }
        public string Remarks { get; set; }
        public bool Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public Nullable<decimal> TotalIncome { get; set; }
        public Nullable<decimal> TotalTaxableAmount { get; set; }
        public Nullable<decimal> NetTaxableAmount { get; set; }
        public Nullable<bool> IsPaid { get; set; }
    }
}
