//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreRegistration
    {
        public int PreRegistrationID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Sex { get; set; }
        public string ContactNumber { get; set; }
        public string MobileNumber { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string RegistrationMode { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool Status { get; set; }
        public Nullable<int> AgeYear { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
