//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaveDymanicPathologyTest
    {
        public int SaveDymanicPathologyTestId { get; set; }
        public Nullable<int> PathologyDynamicTestColumnId { get; set; }
        public string ColumnName { get; set; }
        public string Values1 { get; set; }
        public string Values2 { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public Nullable<int> SubDepartmentId { get; set; }
    }
}
