//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupMemberDiscount
    {
        public int MemberDiscountID { get; set; }
        public int MemberShipType { get; set; }
        public decimal DiscountPercent { get; set; }
        public string Others { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual SetupMemberType SetupMemberType { get; set; }
    }
}
