//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupHospitalDetail
    {
        public int DetailsId { get; set; }
        public string TitleName { get; set; }
        public string HospitalName { get; set; }
        public string Address { get; set; }
        public Nullable<int> WardNo { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string PostBox { get; set; }
        public string TelPhone { get; set; }
        public string WebsiteUrl { get; set; }
        public string HospitalEmail { get; set; }
        public string FaxNumber { get; set; }
        public string ImageLogoName { get; set; }
        public string FilePath { get; set; }
        public string PanNumber { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
