//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupStockSupplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SetupStockSupplier()
        {
            this.StockItemPurchases = new HashSet<StockItemPurchase>();
        }
    
        public int StockSupplierID { get; set; }
        public string StockSupplierName { get; set; }
        public string StockSupplierAddress { get; set; }
        public string StockSupplierConNumber { get; set; }
        public string StockSupplierVatNumber { get; set; }
        public string StockSupplierEmail { get; set; }
        public bool Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Type { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> AccountHeadId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockItemPurchase> StockItemPurchases { get; set; }
    }
}
