//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupAgent
    {
        public int AgentId { get; set; }
        public string AgentFirstName { get; set; }
        public string AgentMiddleName { get; set; }
        public string AgentLastName { get; set; }
        public string AgentAddress { get; set; }
        public string AgentContactNo { get; set; }
        public string AgentMobileNo { get; set; }
        public Nullable<int> ManpowerId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
