//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupMemberShip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SetupMemberShip()
        {
            this.SetupMemberDependents = new HashSet<SetupMemberDependent>();
        }
    
        public int SetupMemberID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string MemberID { get; set; }
        public int MemberTypeID { get; set; }
        public System.DateTime JoinDate { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public int MaximumDependent { get; set; }
        public string Address { get; set; }
        public string MobileNumber { get; set; }
        public string ContactNumber { get; set; }
        public string Gender { get; set; }
        public Nullable<int> BloodGroupID { get; set; }
        public string Email { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Remarks { get; set; }
        public bool Status { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> TotalKitta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SetupMemberDependent> SetupMemberDependents { get; set; }
        public virtual SetupMemberType SetupMemberType { get; set; }
    }
}
