//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_NepCalender
    {
        public int Year { get; set; }
        public Nullable<System.DateTime> StDtEng { get; set; }
        public Nullable<System.DateTime> EndDTEng { get; set; }
        public Nullable<int> NDNepM01 { get; set; }
        public Nullable<int> NDNepM02 { get; set; }
        public Nullable<int> NDNepM03 { get; set; }
        public Nullable<int> NDNepM04 { get; set; }
        public Nullable<int> NDNepM05 { get; set; }
        public Nullable<int> NDNepM06 { get; set; }
        public Nullable<int> NDNepM07 { get; set; }
        public Nullable<int> NDNepM08 { get; set; }
        public Nullable<int> NDNepM09 { get; set; }
        public Nullable<int> NDNepM10 { get; set; }
        public Nullable<int> NDNepM11 { get; set; }
        public Nullable<int> NDNepM12 { get; set; }
    }
}
