//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupFiscalYear
    {
        public int FiscalYearId { get; set; }
        public string FiscalYearBS { get; set; }
        public string FiscalYearAD { get; set; }
        public string IsCurrent { get; set; }
        public System.DateTime FiscalYearStartDate { get; set; }
        public System.DateTime FiscalYearEndDate { get; set; }
        public Nullable<int> PrevId { get; set; }
    }
}
