//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupBank
    {
        public int BankSetupId { get; set; }
        public string BankName { get; set; }
        public string BankCode { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> AccountHeadID { get; set; }
    }
}
