//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupDepartment
    {
        public int DeptID { get; set; }
        public string DeptCode { get; set; }
        public string DeptName { get; set; }
        public string Block { get; set; }
        public string Floor { get; set; }
        public Nullable<int> AssociateDepartmentID { get; set; }
        public bool IsAvailable { get; set; }
        public Nullable<bool> IsSelfBilling { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
