//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupDoctorFee
    {
        public int DoctorFeeID { get; set; }
        public int DoctorID { get; set; }
        public decimal DoctorFee { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> TotalFee { get; set; }
        public Nullable<int> FiscalYear { get; set; }
        public bool Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> HosPer { get; set; }
        public Nullable<int> DocPer { get; set; }
        public Nullable<decimal> HosPerAmt { get; set; }
        public Nullable<decimal> DocPerAmt { get; set; }
        public Nullable<bool> IsCommision { get; set; }
    }
}
