//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupEmergencyFee
    {
        public int FeeId { get; set; }
        public decimal EmergencyFee { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> TotalFee { get; set; }
        public bool Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> FiscalYearId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
