//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupDoctorAvailableTime
    {
        public int DoctorAvailableTimeId { get; set; }
        public int DoctorID { get; set; }
        public string DoctorDays { get; set; }
        public string Shift { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public int CheckPatientPerDay { get; set; }
        public Nullable<int> WebPatientPerDay { get; set; }
        public Nullable<decimal> DoctorFee { get; set; }
        public Nullable<int> MaxTokenNumber { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
