//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupEmployeeMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SetupEmployeeMaster()
        {
            this.SetupEmployeeDepartments = new HashSet<SetupEmployeeDepartment>();
            this.SetupEmployeeShifts = new HashSet<SetupEmployeeShift>();
        }
    
        public int EmployeeMasterId { get; set; }
        public string EmployeeCode { get; set; }
        public int EmployeeTypeId { get; set; }
        public string EmployeeFullName { get; set; }
        public System.DateTime EmployeeDOB { get; set; }
        public string PermanentAddress { get; set; }
        public string EmployeePhone { get; set; }
        public string EmployeeMobile { get; set; }
        public string EmployeeEmail { get; set; }
        public System.DateTime EmployeeJoinDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public bool Status { get; set; }
        public int LoginDepartmentIdnt { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string TemporaryAddress { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public string CountryID { get; set; }
        public string CityName { get; set; }
        public string GenderID { get; set; }
        public Nullable<System.DateTime> DateOfRetirement { get; set; }
        public string IsVolunteer { get; set; }
        public Nullable<int> AccountHeadID { get; set; }
        public Nullable<int> SPAccountHeadID { get; set; }
        public string TypeOfEmployee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SetupEmployeeDepartment> SetupEmployeeDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SetupEmployeeShift> SetupEmployeeShifts { get; set; }
    }
}
