//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupBloodType
    {
        public int BloodTypeId { get; set; }
        public string TypeName { get; set; }
        public string Narration { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
