//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetUpIpdRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SetUpIpdRoom()
        {
            this.IpdRoomStatus = new HashSet<IpdRoomStatu>();
        }
    
        public int IpdRoomId { get; set; }
        public int RoomType { get; set; }
        public int RoomNo { get; set; }
        public int StartBed { get; set; }
        public int EndBed { get; set; }
        public Nullable<decimal> BedAmount { get; set; }
        public string RoomPrefix { get; set; }
        public string RoomSufix { get; set; }
        public string BedSufix { get; set; }
        public string BedPrefix { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IpdRoomStatu> IpdRoomStatus { get; set; }
    }
}
