//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupSection
    {
        public int SectionId { get; set; }
        public string Name { get; set; }
        public string SectionCode { get; set; }
        public int DepartmentId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Status { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
