//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupHospitalFeeDiscount
    {
        public int FeeDiscountId { get; set; }
        public Nullable<int> MaxDay { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool Status { get; set; }
        public int FiscalYearId { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
