//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupDoctorTokenRegister
    {
        public int DoctorTokenID { get; set; }
        public int DoctorID { get; set; }
        public int TokenNumber { get; set; }
        public System.DateTime TokenDate { get; set; }
        public System.TimeSpan ShiftStartTime { get; set; }
        public Nullable<System.TimeSpan> ShiftEndTime { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual SetupDoctorMaster SetupDoctorMaster { get; set; }
    }
}
