//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupMemberType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SetupMemberType()
        {
            this.SetupMemberDiscounts = new HashSet<SetupMemberDiscount>();
            this.SetupMemberShips = new HashSet<SetupMemberShip>();
        }
    
        public int MemberTypeID { get; set; }
        public string MemberTypeName { get; set; }
        public Nullable<System.DateTime> ValidUpto { get; set; }
        public string Status { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SetupMemberDiscount> SetupMemberDiscounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SetupMemberShip> SetupMemberShips { get; set; }
    }
}
