//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupManpower
    {
        public int ManpowerId { get; set; }
        public string ManpowerName { get; set; }
        public string Address { get; set; }
        public string ContactNo { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string WebsiteUrl { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
