//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupOtherTest
    {
        public int SetupOtherTestId { get; set; }
        public string OtherTestName { get; set; }
        public string TestNameRemarks1 { get; set; }
        public string TestNameRemarks2 { get; set; }
        public decimal TestAmount { get; set; }
        public Nullable<decimal> TestAmountForeigner { get; set; }
        public Nullable<decimal> TestTax { get; set; }
        public Nullable<decimal> TestTaxForeigner { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> TaxAmountForeigner { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<decimal> TotalAmountForeigner { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> Status { get; set; }
        public int FiscalYearId { get; set; }
        public Nullable<int> TestTypeID { get; set; }
        public Nullable<int> AccountHeadId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> HosPer { get; set; }
        public Nullable<int> DocPer { get; set; }
        public Nullable<decimal> HosPerAmt { get; set; }
        public Nullable<decimal> DocPerAmt { get; set; }
        public Nullable<bool> IsCommision { get; set; }
        public Nullable<decimal> PayablePercentage { get; set; }
        public Nullable<decimal> PayableTaxTotal { get; set; }
        public Nullable<decimal> PayableGrandTotal { get; set; }
        public Nullable<bool> IsSpecialTest { get; set; }
        public Nullable<decimal> PathoPercentage { get; set; }
        public Nullable<decimal> PathoPerAmount { get; set; }
        public Nullable<decimal> PathoTotalAmount { get; set; }
    }
}
