//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupRoomType
    {
        public int RoomTypeId { get; set; }
        public string RoomTypeName { get; set; }
        public int DepartmentId { get; set; }
        public bool Status { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> AccountHeadId { get; set; }
    }
}
