//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupIpdWard
    {
        public int IpdWardId { get; set; }
        public string WardName { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> BlockId { get; set; }
        public Nullable<int> FloorId { get; set; }
        public string MaleOrFemale { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
