//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemPurchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockItemPurchase()
        {
            this.StockItemPurchaseDetails = new HashSet<StockItemPurchaseDetail>();
        }
    
        public int ItemPurchaseId { get; set; }
        public string ItemOrderId { get; set; }
        public int ItemBillNo { get; set; }
        public int StockSupplierId { get; set; }
        public string Narration { get; set; }
        public bool Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public decimal Amount { get; set; }
        public decimal Discount { get; set; }
        public decimal VatAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public string StockEntryNo { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string JVNumber { get; set; }
        public Nullable<int> JVnumberInt { get; set; }
    
        public virtual SetupStockSupplier SetupStockSupplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockItemPurchaseDetail> StockItemPurchaseDetails { get; set; }
    }
}
