//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemRackSetup
    {
        public int StockItemRackSetupId { get; set; }
        public string RackName { get; set; }
        public Nullable<int> RackNumber { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Narration { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Remarks { get; set; }
    }
}
