//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockBreakage
    {
        public int StockBreakgaeId { get; set; }
        public System.DateTime BreakageEntryDate { get; set; }
        public int ItemId { get; set; }
        public int BreakageQuantity { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Remarks { get; set; }
        public bool Status { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
