//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockReturnOut
    {
        public int ReturnOutId { get; set; }
        public int PurchaseId { get; set; }
        public string PurchaseOrderNo { get; set; }
        public int ItemId { get; set; }
        public decimal ReturnOutQty { get; set; }
        public System.DateTime ReturnOutDate { get; set; }
        public int SupplierId { get; set; }
        public string Remarks { get; set; }
        public bool Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ReturnOutNo { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
