//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockGroupingItemMaster
    {
        public int StockGroupingItemMasterID { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> GroupingId { get; set; }
        public Nullable<int> SubGroupingId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> RackId { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Remarks { get; set; }
        public string Narration { get; set; }
        public Nullable<int> TotalItem { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
