//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockGroupingItemDetail
    {
        public int StockGroupItemDetailsId { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> SerrialNo { get; set; }
        public string Description { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> RackId { get; set; }
        public string PartyName { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Condition { get; set; }
    }
}
