//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemLocationSetup
    {
        public int StockItemLocationId { get; set; }
        public string LocatonName { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> WardID { get; set; }
        public string Narration { get; set; }
        public Nullable<int> BlockId { get; set; }
    }
}
