//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPurchaseOrderDetail
    {
        public int PurchaseOrderDetailId { get; set; }
        public int PurchaseOrderId { get; set; }
        public int ItemId { get; set; }
        public decimal Quantity { get; set; }
        public decimal QuotationPrice { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public int SupplierId { get; set; }
        public int ManufactorerId { get; set; }
        public Nullable<bool> Status { get; set; }
        public int VendorId { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual SetupStockItemEntry SetupStockItemEntry { get; set; }
        public virtual StockPurchaseOrder StockPurchaseOrder { get; set; }
    }
}
