//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemGroupSetup
    {
        public int StockGroupingId { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> FromId { get; set; }
        public Nullable<int> ToId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Narration { get; set; }
    }
}
