//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurgeryCharge
    {
        public int SurgeryChargeId { get; set; }
        public string ChargeName { get; set; }
        public decimal ChargeAmount { get; set; }
        public bool Status { get; set; }
        public decimal Tax { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal Vat { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<int> AccountHeadId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> HosPer { get; set; }
        public Nullable<int> DocPer { get; set; }
        public Nullable<decimal> HosPerAmt { get; set; }
        public Nullable<decimal> DocPerAmt { get; set; }
        public Nullable<bool> IsCommision { get; set; }
        public Nullable<decimal> PayableTaxTotal { get; set; }
        public Nullable<decimal> PayableGrandTotal { get; set; }
        public Nullable<decimal> SurgeonComm { get; set; }
        public Nullable<decimal> SurgeonCommAmount { get; set; }
        public Nullable<decimal> PayablePercentage { get; set; }
        public Nullable<decimal> AnesthiaComm { get; set; }
        public Nullable<decimal> AnesthiaCommAmount { get; set; }
        public Nullable<bool> IsSpecialTest { get; set; }
    }
}
