//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxRangeSetup
    {
        public int TaxRangeID { get; set; }
        public string Type { get; set; }
        public int Percentage { get; set; }
        public string IsMarried { get; set; }
        public decimal Amount { get; set; }
        public decimal Amount1 { get; set; }
    }
}
