//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vital
    {
        public int EmergencyVitalId { get; set; }
        public Nullable<int> EmergencyMasterId { get; set; }
        public string AVPU { get; set; }
        public string Pulse { get; set; }
        public string BP { get; set; }
        public string RR { get; set; }
        public string SPO2 { get; set; }
        public string TPR { get; set; }
        public string Wt { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> VTime { get; set; }
        public string Staff { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
